name: Run unit tests

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y libcunit1-dev liblua5.3-dev lcov

    - name: Build
      run: make

    - name: Run tests
      run: make test
